name: Joey KAriSZma
favicon: null
layout_spectrum: 0.21406121086329222
typography_spectrum: 0.47736170748248696
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7850890974514186
  lightness: 0.8991392836906016
  saturation: 0.9144002229440957
  rhythmicContrast: 0.048886692617088556
purpose: []
